# Generated by Django 4.1.3 on 2022-11-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salda_konti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldakonti',
            old_name='konto',
            new_name='sifra',
        ),
    ]
